#!/bin/bash

sleep 2
cd /root
echo "1" > updatestatus
sleep 2
cd /home/rock
rm -r root
git clone https://github.com/McDaisy/root
cd root
cp -r * /root
cd /root
echo "2" > updatestatus
sleep 2
echo "0" > updatestatus
